services:
  - name: web
    region: eur
    github:
      repo: https://github.com/DjouaherRachid/esgi.render.blueprint.nodejs.git
      branch: main
    env:
      - key: NODE_ENV
        value: production
    buildCommand: npm install && npm run build
    startCommand: npm start

databases:
  - name: my-database
    region: eur
    type: postgres
    env:
      - key: POSTGRES_DB
        fromDatabase: true
      - key: POSTGRES_USER
        fromDatabase: true
      - key: POSTGRES_PASSWORD
        fromDatabase: true

automaticDeploy:
  - serviceID: web
    branch: main

